### ISSUE TITLE
USER STORY: Navbar creation

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#11]
As a **developer** I can **create a navbar** so that **users can navigate the site easily**

## Acceptance Criteria
1. Navbar file is in correct includes folder
2. Navbar contains links to all pages on the site
3. What user is shown differs depending on if they are logged in or not.

## Tasks
- [x] Task 1 - Create includes folder
- [x] Task 2 - Create navbar file
- [x] Task 3 - Include navbar in homepage file

**Comment by seanj06** [comment]
Navbar file created in includes file[e7a17b5](https://github.com/seanj06/Burgers-R-Us-P5/commit/e7a17b54bcd2648868d9c272f912a1b2d83b43c0)
