### ISSUE TITLE
USER STORY: Hero Image

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#12]
As a **developer** I can **add a hero image to the homepage** so that **the site looks appealing for visitors as soon as they enter the site**

## Acceptance Criteria
1. Image is correct size and responsive
2. Image matches theme of site
3. Image has button which brings users to products page

## Tasks
- [x] Task 1 - Add hero image to homepage under navbar
- [x] Task 2 - Add order now button to image 
- [x] Task 3 - Add code to bring users to product page from button

**Comment by seanj06** [comment]
Hero image added to homepage and order now button added - [866b4cf](https://github.com/seanj06/Burgers-R-Us-P5/commit/866b4cfa7cf342f196f44d9b6d97c5ef255e4a40)

**Comment by seanj06** [comment]
Faded hero image added to homepage with order now button - [ff4b6ae](https://github.com/seanj06/Burgers-R-Us-P5/commit/ff4b6aef2c46bd9cf073a0a24408e9fcfa2af9de)
