### ISSUE TITLE
USER STORY: Remove item from cart

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#14]
As a **user** I want **to be able to remove items from my cart** so that **I can remove any unwanted items**

## Acceptance Criteria
1. User is able to remove any added items in cart 
2.  User is redirected back to their cart after deletion
3. User is shown success message with item that was deleted

## Tasks
- [x] Task 1 - Add view code to let user remove product from cart
- [x] Task 2 - Ensure correct HTTP response is returned for correct item removal
- [x] Task 3 - Create user success message on item removal

**Comment by seanj06** [comment]
Remove from cart view and url created - [3dff3ae](https://github.com/seanj06/Burgers-R-Us-P5/commit/3dff3aeebe59f31d8ff7ee0c2446cf3dc36a9c0b)

**Comment by seanj06** [comment]
Http response tested 200 returned on item removal

**Comment by seanj06** [comment]
User message created on remove_item view - [6c531f3](https://github.com/seanj06/Burgers-R-Us-P5/commit/6c531f3e3852320061780ec8808ea471d3450ae2)
