### ISSUE TITLE
USER STORY: Search functionality

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#17]
As a **developer** I can **add search functionality** so that **the user can search for the products they want**

## Acceptance Criteria
1. Users can search for any product keyword from search bar in home page
2. Users are given feedback on whether a product is found or not
3. Users are taken to searched for product on products page

## Tasks
- [x] Task 1 - Add search bar to home page
- [x] Task 2 - Add view code to link search bar to products page
- [ ] Task 3 - Add code to give user feedback if no product is found

**Comment by seanj06** [comment]
Search bar added to navbar - [e7a17b5](https://github.com/seanj06/Burgers-R-Us-P5/commit/e7a17b54bcd2648868d9c272f912a1b2d83b43c0)

**Comment by seanj06** [comment]
View code written to handle search logic for products and error message written for blank input - [e8ba538](https://github.com/seanj06/Burgers-R-Us-P5/commit/e8ba538efe24343c2b86c56c0ac73038302c3c37)

**Comment by seanj06** [comment]
User message written for no matching search query - [586ed01](https://github.com/seanj06/Burgers-R-Us-P5/commit/586ed016fda529275a5506a82efbebbd605499e0)
