### ISSUE TITLE
USER STORY: Home page styling

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#18]
As a **developer** I can **make the home page eye catching** so that **first time and returning users are drawn in**

## Acceptance Criteria
1. Navbar is easy for users to follow, links easy to find
2. Hero image big enough to draw user attention
3. About us section is short and descriptive
4. Contact section contains media links and copyright info. 

## Tasks
- [x] Task 1 - Add navbar 
- [x] Task 2 - Add hero image 
- [x] Task 3 - Add about section
- [x] Task 4 - Add contact us section

**Comment by seanj06** [comment]
Navbar added to base template - [e7a17b5](https://github.com/seanj06/Burgers-R-Us-P5/commit/e7a17b54bcd2648868d9c272f912a1b2d83b43c0)

**Comment by seanj06** [comment]
Hero image added to home page - [ff4b6ae](https://github.com/seanj06/Burgers-R-Us-P5/commit/ff4b6aef2c46bd9cf073a0a24408e9fcfa2af9de)

**Comment by seanj06** [comment]
About text and opening hours section added to home page - [aaf2c04](https://github.com/seanj06/Burgers-R-Us-P5/commit/aaf2c04412eaf4502f5aba8acf529984592cfa6e)

**Comment by seanj06** [comment]
Contact us section added to homepage with link to contact template - [4d64f38](https://github.com/seanj06/Burgers-R-Us-P5/commit/4d64f38d7f0190758941cc6088164508fe713634)
