### ISSUE TITLE
USER STORY: Product page creation

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#19]
As a **developer** I can **create a products page** so that **users can search the site for all available products**

## Acceptance Criteria
1. Users can access products page from navbar and homepage
2. Users can see all available products

## Tasks
- [x] Task 1 - Set up products template
- [x] Task 2 - Add view code for products to be displayed on template
- [x] Task 3 - Style products page using bootstrap cards

**Comment by seanj06** [comment]
Product page created and view code written to display products - [c899afb](https://github.com/seanj06/Burgers-R-Us-P5/commit/c899afba97646e6eeeac6827186e4c35c42adbd6)

**Comment by seanj06** [comment]
Product page styled and customised using bootstrap cards - [d7ae6ef](https://github.com/seanj06/Burgers-R-Us-P5/commit/d7ae6ef450840905ca817a5334dd17bc6718c373)
