### ISSUE TITLE
USER STORY: Install Django and relevant libraries

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#2]
As a **developer** I can **install Django and all other relevant libraries** so that **development on my app can start**

## Acceptance Criteria
1. Django installed correctly from command line
2. All other packages installed from command line
3. All packages freezed into requirements.txt file

## Tasks
- [x] Task 1 - Install Django
- [x] Task 2 - Install other relevant libraries 
- [x] Task 3 - Freeze to requirements.txt file

**Comment by seanj06** [comment]
Django and relevant libraries and installed, requirements.txt file created - [f8fad53](https://github.com/seanj06/Burgers-R-Us-P5/commit/f8fad53cb644c5507ca0548322d085a4ff8be700)
