### ISSUE TITLE
USER STORY: View Products

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#20]
As a **customer** I can **view all food products available** so that **I can choose what I want to purchase**

## Acceptance Criteria
1. Users can navigate to products page from home page and navbar
2. Users can view all products from the products page

## Tasks
- [x] Task 1 - Set up products model to hold food products
- [x] Task 2 - Set up view code to handle product logic
- [x] Task 3 - Set up product template for user to view products
- [ ] Task 4 - Set up product URL to direct user to products page

**Comment by seanj06** [comment]
Products model set up - [5edeb10](https://github.com/seanj06/Burgers-R-Us-P5/commit/5edeb10d766518123d7102546e7369d82b55fe49)
