### ISSUE TITLE
USER STORY: Product Special Offers page

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#22]
As a **customer** I can **view all special offers** so that **I can take advantage of any deals**

## Acceptance Criteria
1. Users can navigate to special offers page from the homepage and products page
2. Special offers page shows users all deals

## Tasks
- [ ] Task 1 - Set up special offers template
- [ ] Task 2 - Set up view code to handle logic
- [ ] Task 3 - Set up URL to direct user to special offer page
- [ ] Task 4
