### ISSUE TITLE
USER STORY: User Notifications

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#25]
As a **developer** I can **set up custom user notifications** so that **users can be notified when they perform an action**

## Acceptance Criteria
1. Users receive notifications when adding or removing item from cart
2. Users receive notifications when signing in or out

## Tasks
- [x] Task 1 - Set up toasts folder in includes file and add toast files
- [x] Task 2 - Include toasts in message div in templates
- [x] Task 3 - Add custom messages for every user action
- [ ] Task 4 - Add session message setting to settings.py

**Comment by seanj06** [comment]
Toast folder and files set up in includes folder - [aaadd5a](https://github.com/seanj06/Burgers-R-Us-P5/commit/aaadd5a24c6be10e578b62884b489eee9aac1f66)

**Comment by seanj06** [comment]
Toast levels and javascript added to base.html - [ac1da1c](https://github.com/seanj06/Burgers-R-Us-P5/commit/ac1da1c155eaddceedb9825b8628652bbfe5b208)

**Comment by seanj06** [comment]
MESSAGE_STORAGE variable added to settings.py - [000ca9e](https://github.com/seanj06/Burgers-R-Us-P5/commit/000ca9e56fc602e14ba90115ec7f84425cdfaf15)
