### ISSUE TITLE
USER STORY: Checkout Template

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#27]
As a **developer** I can **create a checkout template** so that **the user has a page to navigate to to checkout securely**

## Acceptance Criteria
1. Checkout page features checkout form which is linked to checkout model
2. User only able to submit form if all fields are valid
3. User form and checkout page matches rest of site

## Tasks
- [x] Task 1 - Create checkout template inside checkout app
- [x] Task 2 - Render user checkout form which is linked to checkout model
- [x] Task 3 - Style template to match rest of site

**Comment by seanj06** [comment]
Checkout template added with form rendered as crispy form - [01dc1c3](https://github.com/seanj06/Burgers-R-Us-P5/commit/01dc1c3e5bdb6d6f06a53af2b0f0949a2f59f6ad)

**Comment by seanj06** [comment]
Checkout template styled to match rest of site - [f55ba6f](https://github.com/seanj06/Burgers-R-Us-P5/commit/f55ba6f3810b271c1a4628730d2915af192fe732)

**Comment by seanj06** [comment]
Checkout success template styled to match rest of site - [61940b0](https://github.com/seanj06/Burgers-R-Us-P5/commit/61940b06e87b372692fdc36457a4f2a8f8b85ad2)
