### ISSUE TITLE
USER STORY: Checkout Form

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#28]
As a **developer** I can **create a custom user form** so that **users can securely checkout**

## Acceptance Criteria
1. Form has correct attributes attached
2. All fields that are required are set to required
3. Form only valid on correct user input

## Tasks
- [x] Task 1 - Create forms.py file inside checkout app
- [x] Task 2 - Create custom form linking to checkout model
- [x] Task 3 - Create custom widgets for form fields

**Comment by seanj06** [comment]
Forms.py file created , Orderform created that links to Order model and widgets and attrs added for relevant fields- [335d316](https://github.com/seanj06/Burgers-R-Us-P5/commit/335d3161230a19da87edbfd4ae90bb423821fdde)
