### ISSUE TITLE
USER STORY: Render Stripe Field To Template

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#29]
As a **developer** I can **render a stripe field on any relevant templates** so that **users have a way to checkout using a payment method with stripe**

## Acceptance Criteria
1. Users are shown stripe field on the checkout view
2. Secret Api key does not get into production commit

## Tasks
- [x] Task 1 - Add stripe js to base template
- [x] Task 2 - Add stripe API keys to view to render to template
- [x] Task 3 - Create stripe elements javascript file to create stripe field and cards.

**Comment by seanj06** [comment]
Stripe elements js file created - [bf7e07e](https://github.com/seanj06/Burgers-R-Us-P5/commit/bf7e07e671b8ac72c4dd61e992c19339c73c81c9)
