### ISSUE TITLE
USER STORY: Create Django Project And App

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#3]
As a **developer** I can **create a new django project and app** so that **I can start development on my project**

## Acceptance Criteria
1. New django project created with appropriate name
2. New django app created with appropriate name
3. New app added to installed apps in settings.py

## Tasks
- [ ] Task 1 - Create new Django project from command line
- [ ] Task 2 - Create new django app from command line
- [ ] Task 3 - Add new django app to installed apps in settings.py
