### ISSUE TITLE
USER STORY: Checkout Success

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#30]
As a **developer** I can **write code that lets users checkout successfully** so that **the checkout process functions correctly**

## Acceptance Criteria
1. Users are given the option to save their order to their profile.
2. Users are given success message on successful checkout
3. An email is sent to users with order number and delivery time

## Tasks
- [x] Task 1 - Set up checkout success view
- [x] Task 2 - Set up checkout success url
- [x] Task 3 - Set up checkout success template
- [x] Task 4 - Render order details on checkout success page

**Comment by seanj06** [comment]
Checkout success view created - [189b4c0](https://github.com/seanj06/Burgers-R-Us-P5/commit/189b4c0576d24b7cbb4f91d7b9343791719ae404)

**Comment by seanj06** [comment]
Checkout success url and template created - [f253a9a](https://github.com/seanj06/Burgers-R-Us-P5/commit/f253a9abfde41a2dff6e3e29bcc61233370e4330)
