### ISSUE TITLE
USER STORY: Webhooks

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#31]
As a **developer** I can **set up webhooks** so that **I can ensure an order is created in the database even if a problem occurs while the user is making an order**

## Acceptance Criteria
1. Webhook class contains payment intent succeeded method
2. Webhook class contains payment fail method
3. Webhooks tested to ensure functionality

## Tasks
- [x] Task 1 - Create Webhook handler.py file
- [x] Task 2 - Create custom stripe webhook class
- [x] Task 3 - Create __init__ method inside class
- [x] Task 4 - Create payment intent succeeded and fail methods inside class
- [x] Task 5 - Create url for webhook class
- [x] Task 6 - Create webhooks.py file and enter modified stripe documentation code

**Comment by seanj06** [comment]
webhook handler.py file created - [4c0a4b2](https://github.com/seanj06/Burgers-R-Us-P5/commit/4c0a4b2bb29dfacda6d6e12feebb5186332761ca)

**Comment by seanj06** [comment]
Webhook url created - [232f6c7](https://github.com/seanj06/Burgers-R-Us-P5/commit/232f6c7369e96a9bf991f74bb8d269d83038d527)
