### ISSUE TITLE
USER STORY: Profile app

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#32]
As a **developer** I can **create a profile app** so that **user profiles can be organised into their own models views and urls**

## Acceptance Criteria
1. Profile app created from terminal
2. Profile app is added to installed apps
3. Profile app added to main URL file

## Tasks
- [x] Task 1 - Create profile app from terminal
- [x] Task 2 - Add profile app to installed apps
- [x] Task 3 - Add profile app to main urls file

**Comment by seanj06** [comment]
Profile app created and added to installed apps - [aa3f90f](https://github.com/seanj06/Burgers-R-Us-P5/commit/aa3f90f6ef80b4f24a1c7247c2c441ea6a1e08bb)

**Comment by seanj06** [comment]
Profile url.py file created and added to main urls.py file - [b71b2c1](https://github.com/seanj06/Burgers-R-Us-P5/commit/b71b2c1612d558db39d8e18ee8e83de2c2bf71d7)
