### ISSUE TITLE
USER STORY: Profile Model

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#33]
As a **developer** I can **create a profile model ** so that **users can access their delivery and order information and history**

## Acceptance Criteria
1. Profile model is linked to User model
2. Profile model is linked to Order model

## Tasks
- [x] Task 1 - Create user model in profiles app in models.py
- [x] Task 2 - Link User django model to profile app via onetoone field
- [x] Task 3 - Link order model to profile model
- [x] Task 4 - Migrate model to database

**Comment by seanj06** [comment]
User model created and linked to django User model - [7b2dd8c](https://github.com/seanj06/Burgers-R-Us-P5/commit/7b2dd8c844916c98b5a1d9eb5535478e9ead2ff7)

**Comment by seanj06** [comment]
user profile field created on Order model and linked to Profile Model - [455f171](https://github.com/seanj06/Burgers-R-Us-P5/commit/455f17120ef85a11631deef7e2ec09ea6a870f58)
