### ISSUE TITLE
USER STORY: Profile View

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#34]
As a **developer** I can *set up profile views** so that **the logic can be handled for the profile app**

## Acceptance Criteria
1. Home view is set up to render profile page
2. Url is added for profile home view

## Tasks
- [x] Task 1 - Set up home view in views.py
- [x] Task 2 - Add URL for home view
- [x] Task 3 - LInk template to home view

**Comment by seanj06** [comment]
Profile home view created with template and url - [b71b2c1](https://github.com/seanj06/Burgers-R-Us-P5/commit/b71b2c1612d558db39d8e18ee8e83de2c2bf71d7)
