### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#37]
As a **user** I can **contact the restaurant** so that **I can let them know about any issues**

## Acceptance Criteria
1. Users can access contact form from homepage
2. Users can choose from select boxes to narrow down issue

## Tasks
- [x] Task 1 - Create contact model
- [x] Task 2 - Create contact form
- [x] Task 3 - Create contact template and render form

**Comment by seanj06** [comment]
Contact model created - [6ea1542](https://github.com/seanj06/Burgers-R-Us-P5/commit/6ea1542f9233fb71b07aaa318a3ba8a6116dedc0)

**Comment by seanj06** [comment]
Contact from created - [3715862](https://github.com/seanj06/Burgers-R-Us-P5/commit/3715862a9da6fd5f5dd7914610ec288f885ea1dd)

**Comment by seanj06** [comment]
Contact and contact-success templates created - [2c360be](https://github.com/seanj06/Burgers-R-Us-P5/commit/2c360bee499b458122e1c61774753c5fa557ca43)
