### ISSUE TITLE
USER STORY: Create a review

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#38]
As a **user** I can **create a review** so that **I can share my thoughts on my food order**

## Acceptance Criteria
1. Users can access review page from homepage
2. Users can only write a review if logged in
3. Users can rate restaurant from 1 to 5 stars

## Tasks
- [x] Task 1 - Create view code for user to add a review
- [x] Task 2 - Create review form for user to write a review
- [ ] Task 3 - Create review model to store user reviews in database

**Comment by seanj06** [comment]
Review model created - [9b33c05](https://github.com/seanj06/Burgers-R-Us-P5/commit/9b33c05a4030a4701b96e3f1ba242917e1663da6)
