### ISSUE TITLE
USER STORY: Install Allauth

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#4]
As a **developer** I can **install allauth** so that **users can make an account and sign in**

## Acceptance Criteria
1. Allauth installed from command line
2. Allauth added to installed apps in settings.py
3. Alluth freezer to requirements.txt

## Tasks
- [x] Task 1 - Install allauth from command line
- [x] Task 2 - Add allauth to installed apps in settings.py
- [x] Task 3 - Pip freeze allauth package into requirements.txt
