### ISSUE TITLE
USER STORY: Add Products to site

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#42]
As a **staff member** I can **add products to the site** so that **the site is kep updated with the latest products**

## Acceptance Criteria
1. Form is linked to Food Model
2. View and template code is added to ensure only superusers have access to form

## Tasks
- [x] Task 1 - Create Add products form linked to Food Model
- [x] Task 2 - Render form to template
- [x] Task 3 - Ensure only superusers have access to form

**Comment by seanj06** [comment]
Product form created and linked to Food model - [835b83d](https://github.com/seanj06/Burgers-R-Us-P5/commit/835b83dbc23d828e997b4f7457d6ac2fe1e4987d)

**Comment by seanj06** [comment]
Add product template created and form rendered - [286f636](https://github.com/seanj06/Burgers-R-Us-P5/commit/286f636e3c5cfaea6c9fcf1d5d1411c05a9b3158)

**Comment by seanj06** [comment]
View and template code added to ensure only superuser have access to form - [0547a17](https://github.com/seanj06/Burgers-R-Us-P5/commit/0547a173878ac171414c1c981a582e4ea79ef41a)
