### ISSUE TITLE
USER STORY: Finish styling home page

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#45]
As a *developer** I can **finish the styling on the home page** so that **the user has a good impression when entering the site**

## Acceptance Criteria
1. Footer is added to homepage
2. Ensure all site links work
3. Ensure site is fully responsive

## Tasks
- [x] Task 1 - Add footer to homepage
- [x] Task 2 - Ensure responsiveness on all screens
- [x] Task 3 - Ensure all links including navbar work

**Comment by seanj06** [comment]
Footer added to homepage - [09e7815](https://github.com/seanj06/Burgers-R-Us-P5/commit/09e7815598c6ea21e7f5b768bb33573cbaf4e5cf)

**Comment by seanj06** [comment]
Css and media query tidy up for homepage done - [aa50e52](https://github.com/seanj06/Burgers-R-Us-P5/commit/aa50e52832dccb4af48041089d9ea58d85c3dac7)
