### ISSUE TITLE
USER STORY: Finish styling cart page

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#46]
As a **developer** I can **finish styling the cart page** so that **it matches the rest of the site theme**

## Acceptance Criteria
1. Cart page is fully responsive on all screen sizes
2. Page them matches rest of site
3. All page functionality works correctly

## Tasks
- [x] Task 1 - Esnure page is fully responsive
- [x] Task 2 - Ensure page styling matches rest of site
- [x] Task 3 - Ensure all functionality works correctly

**Comment by seanj06** [comment]
Media query and layout tidy up done on cart template to ensure responsiveness and functionality - [9ad60f7](https://github.com/seanj06/Burgers-R-Us-P5/commit/9ad60f7ae8c8ab412ce8592581ee5e321dad26cd)
