### ISSUE TITLE
USER STORY: Finish styling allauth pages

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#47]
As a **developer** I can **finish styling the allauth pages** so that **the pages match the theme of the rest of the site**

## Acceptance Criteria
1. All pages match the theme of the rest of the site
2. All pages are responsive on all screen sizes and no content is blocked by page header
3. All correct user toast messages are shown

## Tasks
- [x] Task 1 - Style all allauth pages to ensure they match the rest of the site
- [x] Task 2 - Ensure all pages are responsive
- [x] Task 3 - Ensure users are shown correct toast messages on login/logout

**Comment by seanj06** [comment]
Finish styling allauth pages and ensured responsiveness - [ddc73ee](https://github.com/seanj06/Burgers-R-Us-P5/commit/ddc73eeb18aab3b7b1545cd980818ab213ab03d6)
