### ISSUE TITLE
USER STORY: Finish stying product pages

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#48]
As a **developer** I can **finish styling the product pages** so that **the pages match the rest of the site**

## Acceptance Criteria
1. Product pages match the rest of the site
2. Pages are fully responsive on all screen sizes
3. Users are shown correct toast messages
4. Only authorized users can access certain features

## Tasks
- [x] Task 1 - Ensure product and product detail pages match the rest of the site
- [x] Task 2 - Ensure all pages are fully responsive
- [x] Task 3 - Ensure users are shown correct messages 
- [x] Task 4 - Add login required and request.user checks for authorization

**Comment by seanj06** [comment]
Css and media queries added to product pages to ensure full responsiveness - [76b5e30](https://github.com/seanj06/Burgers-R-Us-P5/commit/76b5e30f12372d9d5afac7317f2ffefcd9ab06a1)
