### ISSUE TITLE
USER STORY: Custom Error Pages

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#49]
As a **developer** I can **add custom error pages** so that **the error pages users see match the rest of the site**

## Acceptance Criteria
1. All error pages match the theme of the rest of the site
2. All error pages show the user a home button to navigate back to the home page

## Tasks
- [x] Task 1 - Create custom 500 server error page
- [x] Task 2 - Create custom 403 action forbidden error page
- [x] Task 3 - Create custom 404 page not found error page

**Comment by seanj06** [comment]
Custom 500 error page created - [b4479f7](https://github.com/seanj06/Burgers-R-Us-P5/commit/b4479f78c6b720763dbb4979489993e0a8578cde)

**Comment by seanj06** [comment]
Custom 404 error page created - [60b6eae](https://github.com/seanj06/Burgers-R-Us-P5/commit/60b6eaee0196e0b6614246f94cff71e537f46174)

**Comment by seanj06** [comment]
Custom 403 error page created - [60b6eae](https://github.com/seanj06/Burgers-R-Us-P5/commit/60b6eaee0196e0b6614246f94cff71e537f46174)
