### ISSUE TITLE
USER STORY: Python Automated testing

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#53]
As a **developer** I can **write automated tests** so that **I can ensure my code functions correctly**

## Acceptance Criteria
1. All files in apps are tested 
2. At least 75% overall coverage between all apps

## Tasks
- [x] Task 1 - Write automated tests for checkout app
- [x] Task 2 - Write automated tests for cart app
- [x] Task 3 - Write automated tests for contact app
- [x] Task 4 - Write automated tests for products app
- [x] Task 4 - Write automated tests for profiles app
- [x] Task 4 - Write automated tests for review app

**Comment by seanj06** [comment]
Unit tests written for cart app - [13ead54](https://github.com/seanj06/Burgers-R-Us-P5/commit/13ead548eb161eac2e3ff283fb6c287dc05a1970)

**Comment by seanj06** [comment]
Unit tests written for checkout app - [b5538e2](https://github.com/seanj06/Burgers-R-Us-P5/commit/b5538e27ae0179c4bb558460cbcd8ef53747937d)

**Comment by seanj06** [comment]
Unit tests written for contact app.- [22e37dd](https://github.com/seanj06/Burgers-R-Us-P5/commit/22e37dd5c7e24051c0d3d3263f57e5046be82137)

**Comment by seanj06** [comment]
Unit tests written for product app - [9f36799](https://github.com/seanj06/Burgers-R-Us-P5/commit/9f3679917d743a3023c413a47d61bff0fde0548c)

**Comment by seanj06** [comment]
Unit tests written for profiles app - [73e9135](https://github.com/seanj06/Burgers-R-Us-P5/commit/73e91350867d2a81aef918e121fd67cf26129846)

**Comment by seanj06** [comment]
Unit tests written for review app - [9baea4b](https://github.com/seanj06/Burgers-R-Us-P5/commit/9baea4b44817d890faed0ff986caaf0d3956bed3)
