### ISSUE TITLE
USER STORY: Code validation

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#55]
As a **developer ** I can **validate my code** so that **it passes through code validators and follows best practices**

## Acceptance Criteria
1.  All HTML code passes validation
2. All CSS code passes validation
3. All python code passes validation
4. All javascript code passes validation

## Tasks
- [ ] Task 1 - Put all HTML code through w3c validator and make changes as needed to ensure validation
- [ ] Task 2 - Put all CSS code through jigsaw validator and make changes as needed to ensure validation
- [ ] Task 3 - Put all JS code through jshint validator and make changes as needed to ensure validation
- [ ] Task 4 - Put all Python code through pylint validator and make changes as needed to ensure validation

**Comment by seanj06** [comment]
All python code validated - [a258158](https://github.com/seanj06/Burgers-R-Us-P5/commit/a258158b1f0e93dd41be863b90b2bc0d450b45af)

**Comment by seanj06** [comment]
All js code validated - [a357b3d](https://github.com/seanj06/Burgers-R-Us-P5/commit/a357b3d68d5a12d00a6cbc923c14f4cbd1d1689e)

**Comment by seanj06** [comment]
all html code validated - [cc06a40](https://github.com/seanj06/Burgers-R-Us-P5/commit/cc06a40dc1493eda144891e4bff2b6b97b9329d2)
