### ISSUE TITLE
USER STORY: Create new Heroku app

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#7]
As a **developer** I can **create a new Heroku app** so that **my site can be deployed correctly**

## Acceptance Criteria
1. New Heroku app created
2. Relevant config vars entered for deployment
3. Disable collect static initially set as a config var before was bucket is set up.
4. Link github repo to heroku app

## Tasks
- [x] Task 1 - Create a new Heroku app
- [x] Task 2 - Link app to github repository
- [x] Task 3 - Add relevant config vars
- [x] Task 4 - Add Heroku app name to allowed hosts in settings.py

**Comment by seanj06** [comment]
new Heroku app created and allowed host added to settings - [a3e43f1](https://github.com/seanj06/Burgers-R-Us-P5/commit/a3e43f171922a197479f123b04edeabd751c1622)

**Comment by seanj06** [comment]
Config vars added to Heroku and app successfully deployed
