### ISSUE TITLE
USER STORY: Static File Hosting

### ISSUE THREAD

**Issue by seanj06** [seanj06/Burgers-R-Us-P5#8]
As a **developer** I can **set up an aws bucket and link it to my deployed heroku app** so that **it serves the static files of my deployed app**

## Acceptance Criteria
1. The deployed site launches correctly with static files.

## Tasks
- [x] Task 1 - Set up aws bucket and get secret keys
- [x] Task 2 - Add aws keys to heroku config vars
- [x] Task 3 - Remove disable collectstatic config vars

**Comment by seanj06** [comment]
Aws settings added to settings.py - [f98e709](https://github.com/seanj06/Burgers-R-Us-P5/commit/f98e7096b58331a521ca297a6fff011dd9b3058a)

**Comment by seanj06** [comment]
Secret keys added to heroku and app deployed with static file hosting
